### ISSUE TITLE
End points - Friendships

### ISSUE THREAD

**Issue by samjam48** [syncify-team/syncify-back-end#16]
**Friend Relationship between two users**
- [x] - migrations table
- [x] - Create
- [x] - Read
- [x] - Delete

**Comment by aliahsan07** [comment]
I'm not sure about the 5th point @samjam48 is that referring to from frontend or the fact that we can update a current row of friendships table from anywhere?

**Comment by aliahsan07** [comment]
might not make sense to update a friendship between users, does it? People are either friends or they're not in which case we destroy that record, so possibly there isn't a need to update a particular record of friendships table.
