### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by samjam48** [syncify-team/syncify-back-end#34]
Enable hot reloading of the server.
Parcel or nodemon

**Comment by samjam48** [comment]
details of parcel here
https://parceljs.org/

**Comment by vine-d** [comment]
Created a new brach from development, called add-parcel.
Parcel is set on app.js runs with npm start

**Comment by vine-d** [comment]
It should be working with parcel bundler.
Need someone to have a look and test.
