### ISSUE TITLE
bug - authentication connection

### ISSUE THREAD

**Issue by samjam48** [syncify-team/syncify-back-end#45]
Error connecting to port 80 using docker

Using postman to test endpoints I get problems.

Auth0 causing errors 🤷‍♀️

`Unhandled rejection Error: connect ECONNREFUSED 127.0.0.1:5432`

----
Update.

If you add:
`console.log(extraParams.id_token)`
to line 47 of app.js and use the token that get's logged. then it works.
So the app is not updating the bearer token into local storage dynamically and needs to fix this.

**Comment by JedraPeake** [comment]
Can we close this:
- the error was due to the missing auth0 issuer environment variable
- the local token issue, shouldn't be an issue once passport is removed
